[package]
name = "docker_networking_tests"
version = "0.1.0"
edition = "2021"
authors = ["Cameron VanHouzen <cavanhouzen@midmark.com>"]

[dependencies]
axum = "0.7"
tokio = { version = "1.0", features = ["full"] }
reqwest = "0.11"
tracing-subscriber = "0.3"
